version: '3.7'

services:
  pyspark:
    platform: linux/amd64
    container_name: pyspark
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888" # Jupyter Lab
      - "4040:4040" # Spark UI
    env_file:
      - .env
    environment:
      JUPYTER_ENABLE_LAB: yes
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    restart: unless-stopped
    tty: true
    command: >
      bash -c "
      start-notebook.sh --NotebookApp.token=""
      "
    volumes:
      - type: bind
        source: ./workspace/
        target: /home/jovyan/work